openapi: 3.0.2
info:
  description: University of Arizona linking server
  title: linking
  version: 1.0.0
servers:
  - url: http://linking.cs.arizona.edu
    description: University of Arizona linking server

components:
  schemas:
    searchResponse:
      type: array
      items:
        type: object
        properties:
          score:
            type: number
            format: float
          datamartId:
            type: string
          datasetId:
            type: string
          variableId:
            type: string
          variableDescription:
            type: string
            
paths:
  /search:
    get:
      summary: Link
      description: ""
      parameters:
        - name: query
          in: query
          description: a match by example
          required: true
          schema:
            type: string
        - name: maxHits
          in: query
          description: maximum number of matches to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/searchResponse"
